import { Geist, Geist_Mono } from "next/font/google";
 import "./globals.css";
 import NavBar from "@/components/NavBar/NavBar";
 import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Project Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (    
    <html lang="en">
      <link rel="icon" href="/" />
      <body >
        <div className="mainContainer">
          <NavBar/>
          <div>
          {children}
          </div>
        <Footer/>
        </div>
      </body>
    </html>
  );
}
